### ISSUE TITLE
Still waiting for Code

### ISSUE THREAD

**Issue by usmaann** [orestxherija/smm4h2018#1]
Hello Brother, you have written a nice paper.

could you please upload the code please for others for learning purpose. thanks

**Comment by orestxherija** [comment]
I plan to to have the code uploaded in the following two weeks. I apologize for the delay, I was (lazily) trying to update the code to be compatible with the latest version of Keras.

**Comment by usmaann** [comment]
Can you upload the current code which is available currently with you? Thanks in advance

**Comment by usmaann** [comment]
Hello, seems you didn't get time to upload the code??

**Comment by orestxherija** [comment]
I have finally uploaded the code for my submissions to the SMM4H 2018 shared task.
